### ISSUE TITLE
`enum` type support 

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/domapping#4]
Running `domapping` on our example MARC21 JSON Schema leads to an error due to unsupported `enum`:

``` console
$ workon domapping
$ cd dojson/contrib/marc21/schemas
$ domapping schema_to_mapping ./bd20x24x.json
[...]
domapping.errors.JsonSchemaSupportError: ERROR Schema has no "type" field 
   IN ./bd20x24x.json/former_title/items/title_added_entry
```

The corresponding JSON Schema bit:

```
        "former_title": {
            "description": "Former Title",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title_added_entry": {
                        "enum": ["Added entry", "No added entry"]
                    },
```

Possible techniques on how we could solve this:
- add explicit types to our schemas? 
- attempt to analyse the types of objects under enum?
- simply assume strings everywhere when enum is encountered?
- supply a CLI option to specify "default type" if none is provided?

**Comment by nharraud** [comment]
I think providing support for string and numbers without `type` field is easy enough. Maybe we can add `null` support as well, I have to check how elasticsearch handles a `null` on a typed field. 
However we should force failure for anything else than string and number without specifying the type. Json-schema allows combination of number and strings, and it would be too complicated to guess which type is the valid one (especially with string containing numbers).
